- name: Create Infra for Roboshop
  hosts: all
  connection: local
  become: yes
  vars:
    ami_id: "ami-0220d79f3f480ecf5"
    sg_id: "sg-080704b1b6c62ec5a"
    env: "dev"
    action: "create"
    domain_name: tzpcsystems.xyz
    instances:
      - mongodb
      - catalogue
  tasks:
    - name: Create Servers
      amazon.aws.ec2_instance:
        name: "{{ item }}-{{ env }}"
        region: us-east-1
        instance_type: t3.micro
        image_id: "{{ ami_id }}"
        security_group: "{{ sg_id }}"
        tags:
          Product: Roboshop
          Component: "{{ item }}"
          Env: "{{ env }}"
          Name: "{{ item }}-{{ env }}"
      loop: "{{ instances }}"
      register: instances_output
      when:
      - action == 'create'
        
    - name: Print Instance Output
      ansible.builtin.debug:
        msg: "{{ instances_output }}"

    - name: Add DNS for servers
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}-{{ env }}.{{ domain_name }}"
        type: A
        ttl: 1
        overwrite: true
        value: "{{ item.instances[0].private_ip_address }}"
        # value: "{{ item.instances[0].public_ip_address }}"
        wait: false
      loop: "{{ instances_output.results }}"
      when:
      - action == 'create'

    - name: Add DNS for servers
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}-{{ env }}.{{ domain_name }}"
        type: A
        ttl: 1
        overwrite: true
        value: "{{ item.instances[0].public_ip_address }}"
        wait: false
      loop: "{{ instances_output.results }}"
      when:
      - item.item == 'frontend'
      - action == 'create'

# Destroy

    - name: Delete Route53 Records for Frontend
      amazon.aws.route53:
        state: absent
        zone: "{{ domain_name }}"
        record: "{{ item }}-{{ env }}.{{ domain_name }}"
        type: A
        ttl: 1
      loop: "{{ instances }}"
      when: 
      - action == "destroy"
      - item == "fromtend"

    - name: Delete Route53 Records other than Frontend
      amazon.aws.route53:
        state: absent
        zone: "{{ domain_name }}"
        record: "{{ item }}-{{ env }}.{{ domain_name }}"
        type: A
        ttl: 1
      loop: "{{ instances }}"
      when: 
      - action == "destroy"

    - name: Destroy Ec2 instances
      amazon.aws.ec2_instance:
        state: absent
        name: "{{ item }}-{{ env }}"
        region: us-east-1
        wait: true
      loop: "{{ instances }}"
      when: action == "destroy"
